export const projects = [
  {
    name: "Contracted Site",
    slug: "contracted-site",
    displayOrder: 3,
    imageSize: { width: 769, height: 773 },
    description:
      "A portfolio and storefront concept for a photographer, with space to showcase work and sell photography and video resources.",
    mainImage: "assets/img/projects/Brandon.png",
    img1: "",
    img2: "",
    img3: "",
    summaries: [{ summary: 'The site is designed to present a photographer\'s work and offer photography and video resources. The project combines a portfolio presentation with a planned storefront.' }],
    stack: [],
  },
  {
    name: "Candy Co.",
    slug: "candy-co",
    displayOrder: 1,
    imageSize: { width: 1881, height: 866 },
    description:
      "A mock online candy store.",
    mainImage: "assets/img/projects/candyco-homepage.png",
    gallery: [
      { src: "/assets/img/projects/candyco1.png", width: 1710, height: 835, alt: "Candy Co. product listing with Add to Cart buttons", caption: "Product listing" },
      { src: "/assets/img/projects/candyco2.png", width: 1708, height: 829, alt: "Candy Co. sign-in form", caption: "Sign-in screen" },
      { src: "/assets/img/projects/candyco3.png", width: 1707, height: 826, alt: "Candy Co. checkout and shipping form", caption: "Checkout layout" },
    ],
    img1: "",
    img2: "",
    img3: "",
    summaries: [{ summary: 'The mock storefront includes a promotional homepage, product listing, sign-in screen, and checkout layout.' }],
    stack: [
      "/assets/img/svg/react.svg",
      "/assets/img/svg/redux.svg",
      "/assets/img/svg/sequelize.svg",
      "/assets/img/svg/stripe.svg",
      "/assets/img/svg/tailwind.svg",
    ],
  },
  {
    name: "Fitness-TS",
    slug: "fitness-ts",
    displayOrder: 2,
    imageSize: { width: 1902, height: 943 },
    description:
      "A mock gym website built with TypeScript, React, and Tailwind CSS.",
    mainImage: "assets/img/projects/fitness-homepage.png",
    img1: "",
    img2: "",
    img3: "",
    summaries: [{ summary: 'The landing page introduces the gym and its fitness offering.' }],
    stack: [
      "/assets/img/svg/typescript.svg",
      "/assets/img/svg/react.svg",
      "/assets/img/svg/tailwind.svg",
    ],
  },
  {
    name: "Flock",
    slug: "flock",
    displayOrder: 0,
    imageSize: { width: 1901, height: 879 },
    description:
      "A progressive web app concept for finding group runs.",
    mainImage: "assets/img/projects/flock-app.png",
    img1: "",
    img2: "",
    img3: "",
    summaries: [{ summary: 'The concept brings group run events into one place for runners to explore.' }],
    stack: [
      "/assets/img/svg/react.svg",
      "/assets/img/svg/redux.svg",
      "/assets/img/svg/sequelize.svg",
      "/assets/img/svg/socketio.svg",
      "/assets/img/svg/leaflet.svg",
    ],
  },
];
