export const projects = [
  {
    name: "Contracted Site",
    displayOrder: 3,
    imageSize: { width: 769, height: 773 },
    description:
      "A portfolio and storefront concept for a photographer, with space to showcase work and sell photography and video resources.",
    mainImage: "assets/img/projects/Brandon.png",
    img1: "",
    img2: "",
    img3: "",
    summaries: [{ summary: 'The site is designed to present a photographer\'s work and offer photography and video resources. The project combines a portfolio presentation with a planned storefront.' }],
    stack: [],
  },
  {
    name: "Candy Co.",
    displayOrder: 1,
    imageSize: { width: 1881, height: 866 },
    description:
      "A mock online candy store.",
    mainImage: "assets/img/projects/candyco-homepage.png",
    img1: "",
    img2: "",
    img3: "",
    summaries: [{ summary: 'A mock e-commerce project for a candy store. The project uses React, Redux, Sequelize, Stripe, and Tailwind CSS.' }],
    stack: [
      "/assets/img/svg/react.svg",
      "/assets/img/svg/redux.svg",
      "/assets/img/svg/sequelize.svg",
      "/assets/img/svg/stripe.svg",
      "/assets/img/svg/tailwind.svg",
    ],
  },
  {
    name: "Fitness-TS",
    displayOrder: 2,
    imageSize: { width: 1902, height: 943 },
    description:
      "A mock gym website built with TypeScript, React, and Tailwind CSS.",
    mainImage: "assets/img/projects/fitness-homepage.png",
    img1: "",
    img2: "",
    img3: "",
    summaries: [{ summary: 'A mock gym website built with TypeScript, React, and Tailwind CSS.' }],
    stack: [
      "/assets/img/svg/typescript.svg",
      "/assets/img/svg/react.svg",
      "/assets/img/svg/tailwind.svg",
    ],
  },
  {
    name: "Flock",
    displayOrder: 0,
    imageSize: { width: 1901, height: 879 },
    description:
      "A progressive web app concept for finding group runs.",
    mainImage: "assets/img/projects/flock-app.png",
    img1: "",
    img2: "",
    img3: "",
    summaries: [{ summary: 'A progressive web app concept that helps runners discover group run events. The project uses React, Redux, Sequelize, Socket.io, and Leaflet.' }],
    stack: [
      "/assets/img/svg/react.svg",
      "/assets/img/svg/redux.svg",
      "/assets/img/svg/sequelize.svg",
      "/assets/img/svg/socketio.svg",
      "/assets/img/svg/leaflet.svg",
    ],
  },
];
